apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-career
spec:
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: career_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: career-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: career_platform
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: student-career
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432